name: mutex
description: Mutual exclusion
version: 1.0.1
author: Hoylen Sue <hoylen@hoylen.com>
homepage: https://github.com/hoylen/dart-mutex

environment:
  sdk: '>=1.0.0 <3.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
