name: mutex
description: Mutual exclusion with implementation of normal and read-write mutex
version: 3.0.0
homepage: https://github.com/hoylen/dart-mutex

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.3
